## Load the raw data

In [3]:
import pandas as pd

df = pd.read_csv("../data/raw/pakistan_full_training_dataset.csv")
print(df.shape)
df.head()

(8808, 13)

,OBJECTID_1,Id,OBJECTID,Shape_Leng,Shape_Le_1,Shape_Area,area_km2,longitude,latitude,is_top200,avg_temp_c,avg_precip_mm,label
0,1,0,0,0.0,4734.655069,950522.097801,0.950522,74.061891,34.828994,True,0.22,1.74,0
1,2,0,0,0.0,806.707326,34728.361094,0.034728,74.086340,34.820079,False,-0.81,1.73,0
2,3,0,0,0.0,1202.063357,19693.201851,0.019693,74.071990,34.806459,False,-0.81,1.73,0
3,4,0,0,0.0,2016.005430,206074.467866,0.206074,74.076763,34.857497,True,-0.81,1.73,0
4,5,0,0,0.0,568.308747,21374.534646,0.021375,74.078262,34.861163,False,-0.81,1.73,0

## Check for missing values and duplicates

In [4]:
print(df.isnull().sum())

print("Duplicates:" , df.duplicated().sum())

OBJECTID_1       0
Id               0
OBJECTID         0
Shape_Leng       0
Shape_Le_1       0
Shape_Area       0
area_km2         0
longitude        0
latitude         0
is_top200        0
avg_temp_c       0
avg_precip_mm    0
label            0
dtype: int64
Duplicates: 0

## Drop the unnecessary columns

In [5]:
df_clean = df.drop(columns=['OBJECTID_1', 'Id', 'OBJECTID', 'Shape_Leng', 'Shape_Le_1', 'Shape_Area'])
print(df_clean.shape)
df_clean.columns

(8808, 7)

Index(['area_km2', 'longitude', 'latitude', 'is_top200', 'avg_temp_c',
       'avg_precip_mm', 'label'],
      dtype='str')

## Check basic stats

In [6]:
df_clean.describe()

,area_km2,longitude,latitude,avg_temp_c,avg_precip_mm,label
count,8808.000000,8808.000000,8808.000000,8808.000000,8808.000000,8808.000000
mean,0.015482,74.735862,35.745160,-3.260712,0.905870,0.039850
std,0.079291,1.389030,0.570958,4.077236,0.390379,0.195618
min,0.000009,71.149000,34.482656,-13.370000,0.310000,0.000000
25%,0.000695,73.732636,35.252803,-5.920000,0.650000,0.000000
50%,0.001855,75.149492,35.832366,-3.030000,0.770000,0.000000
75%,0.008926,75.805569,36.116909,-0.460000,1.020000,0.000000
max,3.930649,77.208187,36.926687,11.820000,2.060000,1.000000

## SAVE CLEAN DATA

In [7]:
df_clean.to_csv("../data/processed/pakistan_full_training_dataset_clean.csv", index=False)